-- Automatically fill our database
-- Needs to have tables pre-generated by our spring boot application

-- TRUNCATE tags CASCADE;
-- SELECT * FROM worlds;

INSERT INTO users (id, username, password)
VALUES
(1, 'iamauser', 'password123'),
(2, 'yesmetoo', 'p4ssw0rd');

INSERT INTO tags (id, name)
VALUES
(1, 'Fantasy'),
(2, 'Sci-Fi'),
(3, 'Superhero'),
(4, 'Alternate History'),
(5, 'Horror'),
(6, 'Steampunk');

INSERT INTO worlds (id, name, description)
VALUES
(1, 'Westeros', 'The world of GoT'),
(2, 'Star Wars', 'The world of the Star Wars franchise');

INSERT INTO world_tags(world_id, tag_id)
VALUES
(1,1), -- Westeros is fantasy
(2,2); -- Star wars is sci-fi